@startuml test
!define Devops https://raw.githubusercontent.com/vadivelselvaraj/datanengineer-plantuml-sprites/main/sprites
!includeurl Devops/docker_logo.puml

actor alice
node "<$dataengineer_docker_logo,color=blue>" as docker

alice -> docker

@endumls