@startuml test
!define Devops https://raw.githubusercontent.com/vadivelselvaraj/datanengineer-plantuml-sprites/main/components
!includeurl Devops/common.puml

!define DataEngineerSprites https://raw.githubusercontent.com/vadivelselvaraj/datanengineer-plantuml-sprites/main/sprites
!includeurl DataEngineerSprites/developer_happy.puml
!includeurl DataEngineerSprites/docker_logo.puml

DEVOPS_DOCKER_LOGO(Blue, 1, docker)
DEVOPS_DEVELOPER_HAPPY(Blue, 1, dev)

@endumls