@startuml test

!define Devops https://raw.githubusercontent.com/vadivelselvaraj/datanengineer-plantuml-sprites/main/components
!includeurl Devops/common.puml
!includeurl Devops/docker.puml
!includeurl Devops/dev.puml

DockerContainer(portainer, "Portainer")

DockerContainer(app1, "App")
DockerContainer(app2, "App")

HappyDeveloper(dev, "You")

@enduml