!define DataEngineerSprites https://raw.githubusercontent.com/vadivelselvaraj/datanengineer-plantuml-sprites/main/sprites
!includeurl DataEngineerSprites/docker_logo.puml

!definelong DockerContainer(e_alias, e_label)
skinparam rectangleTextAlignment<<DockerContainer>> center
skinparam componentTextAlignment<<DockerContainer>> center
skinparam componentDefaultTextAlignment<<DockerContainer>> center
skinparam defaultTextAlignment<<DockerContainer>> center
node "==e_label\n<color:blue><$dataengineer_docker_logo></color>\n" <<DockerContainer>> as e_alias
!enddefinelong
